TicketManagementSystem.Web/ViewModels/Package/PackageCreateDefaultModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using TicketManagementSystem.ViewModels.Nominal;

namespace TicketManagementSystem.Web
{
    public class PackageCreateDefaultModel
    {
        [Required(ErrorMessage = "Необхідно обрати колір.")]
        [Display(Name = "Колір")]
        public int ColorId { get; set; }

        [Required(ErrorMessage = "Необхідно обрати серію.")]
        [Display(Name = "Серія")]
        public int SerialId { get; set; }

        [Display(Name = "Номінал")]
        public int NominalId { get; set; }

        [Display(Name = "Перша цифра")]
        [Range(0, 9, ErrorMessage = "Повинно бути число від 0 до 9.")]
        public int? FirstNumber { get; set; }

        [Display(Name = "Примітка")]
        [DataType(DataType.MultilineText)]
        [StringLength(128, ErrorMessage = "Довжина не може перевищувати 128 символів.")]
        public string Note { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Colors { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Series { get; set; }

        [HiddenInput(DisplayValue = false)]
        public IEnumerable<NominalVM> Nominals { get; set; }
    }
}

TicketManagementSystem.Web/ViewModels/Package/PackageCreateSpecialModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using TicketManagementSystem.ViewModels.Nominal;

namespace TicketManagementSystem.Web
{
    public class PackageCreateSpecialModel
    {
        [Display(Name = "Назва")]
        [Required(ErrorMessage = "Необхідно вказати назву пачки.")]
        [StringLength(64, MinimumLength = 2, ErrorMessage = "Назва може бути від 2 до 64 символів.")]
        public string Name { get; set; }
        
        [Display(Name = "Колір")]
        public int? ColorId { get; set; }
        
        [Display(Name = "Серія")]
        public int? SerialId { get; set; }

        [Display(Name = "Номінал")]
        public int? NominalId { get; set; }

        [Display(Name = "Примітка")]
        [DataType(DataType.MultilineText)]
        [StringLength(128, ErrorMessage = "Довжина не може перевищувати 128 символів.")]
        public string Note { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Colors { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Series { get; set; }

        [HiddenInput(DisplayValue = false)]
        public IEnumerable<NominalVM> Nominals { get; set; }
    }
}

TicketManagementSystem.Web/ViewModels/Package/PackageDetailsModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TicketManagementSystem.Web
{
    public class PackageDetailsModel
    {
        [Display(Name = "ID:")]
        public int Id { get; set; }

        [Display(Name = "Назва:")]
        public string Name { get; set; }

        [Display(Name = "Колір:")]
        public string ColorName { get; set; }

        [Display(Name = "Серія:")]
        public string SerialName { get; set; }

        [Display(Name = "Квитків:")]
        public int TicketsCount { get; set; }

        [Display(Name = "Номінал:")]
        public double? Nominal { get; set; }

        [Display(Name = "Перша цифра:")]
        public int? FirstNumber { get; set; }

        [Display(Name = "Примітка:")]
        public string Note { get; set; }

        [Display(Name = "Статус:")]
        public string Status
        {
            get
            {
                var openState = IsOpened ? "Відкрита" : "Закрита";
                var specialState = IsSpecial ? "Спеціальна" : "Звичайна";

                return $"{openState} / {specialState}";
            }
        }

        #region Hidden properties

        [HiddenInput(DisplayValue = false)]
        public bool IsOpened { get; set; }

        [HiddenInput(DisplayValue = false)]
        public bool IsSpecial { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int ColorId { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int SerialId { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int UnallocatedTicketsCount { get; set; }

        #endregion
    }
}

TicketManagementSystem.Web/ViewModels/Package/PackageEditDefaultModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using TicketManagementSystem.ViewModels.Nominal;

namespace TicketManagementSystem.Web
{
    public class PackageEditDefaultModel
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Необхідно обрати колір.")]
        [Display(Name = "Колір")]
        public int ColorId { get; set; }

        [Required(ErrorMessage = "Необхідно обрати серію.")]
        [Display(Name = "Серія")]
        public int SerialId { get; set; }

        [Display(Name = "Номінал")]
        public int NominalId { get; set; }

        [Display(Name = "Перша цифра")]
        [Range(0, 9, ErrorMessage = "Повинно бути число від 0 до 9.")]
        public int? FirstNumber { get; set; }

        [Display(Name = "Примітка")]
        [DataType(DataType.MultilineText)]
        [StringLength(128, ErrorMessage = "Довжина не може перевищувати 128 символів.")]
        public string Note { get; set; }

        [HiddenInput(DisplayValue = false)]
        public bool IsEmpty { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Colors { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Series { get; set; }

        [HiddenInput(DisplayValue = false)]
        public IEnumerable<NominalVM> Nominals { get;set; }
    }
}

TicketManagementSystem.Web/ViewModels/Package/PackageEditSpecialModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using TicketManagementSystem.ViewModels.Nominal;

namespace TicketManagementSystem.Web
{
    public class PackageEditSpecialModel
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Display(Name = "Назва")]
        [Required(ErrorMessage = "Необхідно вказати назву пачки.")]
        [StringLength(64, MinimumLength = 2, ErrorMessage = "Назва може бути від 2 до 64 символів.")]
        public string Name { get; set; }

        [Display(Name = "Колір")]
        public int? ColorId { get; set; }

        [Display(Name = "Серія")]
        public int? SerialId { get; set; }

        [Display(Name = "Номінал")]
        public int? NominalId { get; set; }

        [Display(Name = "Примітка")]
        [DataType(DataType.MultilineText)]
        [StringLength(128, ErrorMessage = "Довжина не може перевищувати 128 символів.")]
        public string Note { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Colors { get; set; }

        [HiddenInput(DisplayValue = false)]
        public SelectList Series { get; set; }

        [HiddenInput(DisplayValue = false)]
        public IEnumerable<NominalVM> Nominals { get; set; }
    }
}

TicketManagementSystem.Web/ViewModels/Package/PackageFilterModel.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using TicketManagementSystem.Business.Enums;
using TicketManagementSystem.Business.Extensions;

namespace TicketManagementSystem.Web
{
    public class PackageFilterModel : IEnumerable<PackageDetailsModel>
    {
        [Display(Name = "Колір")]
        public int? ColorId { get; set; }

        [Display(Name = "Серія")]
        public int? SerialId { get; set; }

        [Display(Name = "Перша цифра")]
        public int? FirstNumber { get; set; }

        [Display(Name = "Статус")]
        public PackageStatusFilter Status { get; set; }
        
        public string ColorName { get; set; }
        public string SerialName { get; set; }

        public SelectList Colors { get; set; }
        public SelectList Series { get; set; }

        public IEnumerable<PackageDetailsModel> Packages { get; set; } = new List<PackageDetailsModel>();

        public IEnumerable<SelectListItem> Numbers
        {
            get
            {
                int[] numbers = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };

                return numbers.Select(n => new SelectListItem { Text = n.ToString(), Value = n.ToString() });
            }
        }

        public bool IsNull()
        {
            return ColorId == null
                && SerialId == null
                && FirstNumber == null;
        }

        public override string ToString()
        {
            if (IsNull())
                return null;

            var sBuilder = new StringBuilder();

            if (!string.IsNullOrEmpty(ColorName))
            {
                sBuilder.Append(ColorName);

                if (!string.IsNullOrEmpty(SerialName) || FirstNumber != null)
                    sBuilder.Append(", ");
            }

            if (!string.IsNullOrEmpty(SerialName))
            {
                sBuilder.Append(SerialName);

                if (FirstNumber != null)
                    sBuilder.Append(", ");
            }

            if (FirstNumber != null)
                sBuilder.Append($"Цифра: {FirstNumber}");

            if (Status != PackageStatusFilter.None)
                sBuilder.Append($", {Status.GetDisplayName()}");

            return sBuilder.ToString();
        }

        #region IEnumerable<T> implementation.

        public IEnumerator<PackageDetailsModel> GetEnumerator()
        {
            return Packages.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return Packages.GetEnumerator();
        }

        #endregion
    }
}

TicketManagementSystem.Web/ViewModels/Package/PackageIndexModel.cs
using System.Collections;
using System.Collections.Generic;
using TicketManagementSystem.Business.Enums;

namespace TicketManagementSystem.Web
{
    public class PackageIndexModel : IEnumerable<PackageDetailsModel>
    {
        public IEnumerable<PackageDetailsModel> Packages { get; set; }
        public PageInfo PageInfo { get; set; }
        public PackagesFilter Filter { get; set; }

        public int TotalPackages { get; set; }
        public int OpenedPackages { get; set; }
        public int SpecialPackages { get; set; }

        public string ClassAll => Filter == PackagesFilter.All ? "active" : "";

        public string ClassOpened
        {
            get
            {
                if (OpenedPackages == 0)
                    return "disabled";

                return Filter == PackagesFilter.Opened ? "active" : "";
            }
        }

        public string ClassSpecial
        {
            get
            {
                if (SpecialPackages == 0)
                    return "disabled";

                return Filter == PackagesFilter.Special ? "active" : "";
            }
        }

        public IEnumerator<PackageDetailsModel> GetEnumerator()
        {
            return Packages.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return Packages.GetEnumerator();
        }
    }
}

TicketManagementSystem.Web/ViewModels/Package/PackageMakeDefaultModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TicketManagementSystem.Web
{
    public class PackageMakeDefaultModel
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Display(Name = "Колір")]
        public int ColorId { get; set; }

        [Display(Name = "Серія")]
        public int SerialId { get; set; }

        [Display(Name = "Перша цифра")]
        [Range(0, 9, ErrorMessage = "Повинно бути число від 0 до 9.")]
        public int? FirstNumber { get; set; }

        public SelectList Colors { get; set; }
        public SelectList Series { get; set; }
    }
}

TicketManagementSystem.Web/ViewModels/Ticket/TicketMoveModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TicketManagementSystem.Web
{
    public class TicketMoveModel
    {
        // Hidden.
        public int Id { get; set; }       
        public string Number { get; set; }       
        public int PackageId { get; set; }
        public bool IsUnallocated { get; set; }

        [Display(Name = "Оберіть пачку")]
        public SelectList Packages { get; set; }
    }
}

TicketManagementSystem.Web/Areas/Api/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using TicketManagementSystem.Business.DTO;
using TicketManagementSystem.Business.Enums;
using TicketManagementSystem.Business.Interfaces;
using static TicketManagementSystem.Web.Areas.Api.Models.Extensions;

namespace TicketManagementSystem.Web.Areas.Api.Controllers
{
    [RoutePrefix("api/Package")]
    [Authorize(Roles = "Admin")]
    public class PackageController : BaseApiController
    {
        private readonly IPackageService _packageService;
        private readonly ITicketService _ticketService;
        private readonly IPackageValidationService _packageValidationService;

        public PackageController(IPackageService packageService, ITicketService ticketService, IPackageValidationService packageValidationService)
        {
            _packageService = packageService;
            _ticketService = ticketService;
            _packageValidationService = packageValidationService;
        }

        [HttpGet, AllowAnonymous]
        public IHttpActionResult GetCount() => Ok(_packageService.GetCount());

        [HttpGet, AllowAnonymous]
        public IHttpActionResult GetAll(int skip = 0, int take = 30, PackagesFilter filter = PackagesFilter.All)
        {
            return OkOrNoContent(_packageService.GetPackages(skip, take, filter));
        }

        [HttpGet, AllowAnonymous]
        public IHttpActionResult Filter([FromUri]PackageFilterModel filter)
        {
            if (filter == null || filter?.IsNull() == true)
                return BadRequest();

            return OkOrNoContent(_packageService.Filter(Mapper.Map<PackageFilterDTO>(filter)));
        }

        [HttpGet, AllowAnonymous, Route("Get/{id?}", Name = "PackageById")]
        public IHttpActionResult Get(int id)
        {
            return OkOrNotFound(_packageService.GetPackage(id));
        }

        [HttpGet, AllowAnonymous]
        public IHttpActionResult GetTickets(int id)
        {
            return OkOrNoContent(_packageService.GetPackageTickets(id, true));
        }

        [HttpGet, AllowAnonymous]
        public IHttpActionResult GetUnallocatedTickets(int id)
        {
            return OkOrNoContent(_ticketService.GetUnallocatedTickets(id));
        }

        [HttpGet, AllowAnonymous]
        public IHttpActionResult Search(string name)
        {
            return OkOrNoContent(_packageService.FindByName(name));
        }

        [HttpGet, AllowAnonymous]
        public IHttpActionResult GetCompatiblePackages(int colorId, int serialId, int? firstNumber)
        {
            var packages = _packageService.GetCompatiblePackages(colorId, serialId, firstNumber)?
                .OrderBy(p => p.IsSpecial);

            return OkOrNoContent(packages);
        }

        [HttpDelete]
        public dynamic Delete(int id)
        {
            var package = _packageService.GetPackage(id);

            if (package == null)
                return NotFound();

            _packageService.Remove(id);
            return Ok();
        }

        [HttpPut]
        public dynamic Open(int id)
        {
            var package = _packageService.GetPackage(id);

            if (package == null)
                return NotFound();

            if (package.IsOpened)
            {
                ToModelState(new[] { "Пачка й так відкрита." }, ModelState);
                return BadRequestWithErrors(ModelState);
            }

            _packageService.OpenPackage(id);
            return Ok();
        }

        [HttpPut]
        public dynamic Close(int id)
        {
            var package = _packageService.GetPackage(id);

            if (package == null)
                return NotFound();

            if (!package.IsOpened)
            {
                ToModelState(new[] { "Пачка й так закрита." }, ModelState);
                return BadRequestWithErrors(ModelState);
            }

            _packageService.ClosePackage(id);
            return Ok();
        }

        [HttpPut]
        public dynamic MakeSpecial([FromBody]PackageMakeSpecialDTO dto)
        {
            if (ModelState.IsValid)
            {
                var errors = _packageValidationService.Validate(dto);
                ToModelState(errors, ModelState);

                if (ModelState.IsValid)
                {
                    _packageService.MakeSpecial(dto);
                    return Ok();
                }
            }
            return BadRequestWithErrors(ModelState);
        }

        [HttpPut]
        public dynamic MakeDefault([FromBody]PackageMakeDefaultDTO dto)
        {
            if (ModelState.IsValid)
            {
                var errors = _packageValidationService.Validate(dto);
                ToModelState(errors, ModelState);

                if (ModelState.IsValid)
                {
                    _packageService.MakeDefault(dto);
                    return Ok();
                }
            }
            return BadRequestWithErrors(ModelState);
        }

        [HttpPut]
        public dynamic MoveTickets(int id, [FromBody]IEnumerable<int> ticketsIds)
        {
            // TODO: MoveTickets.
            throw new NotImplementedException();
        }
    }
}

TicketManagementSystem.Web/Views/Package/CreateDefault.cshtml
@model PackageCreateDefaultModel

@{
    ViewBag.Title = "Створити пачку";
}

<h2>@ViewBag.Title</h2>

@using (Ajax.BeginForm("Create", new AjaxOptions
{
    UpdateTargetId = "create-result",
    OnBegin = "OnBegin",
    OnSuccess = "OnSuccess",
    OnComplete = "OnComplete"
})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ColorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ColorId, Model.Colors, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ColorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SerialId, Model.Series, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SerialId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NominalId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="NominalId" name="NominalId" class="form-control">
                    @foreach (var item in Model.Nominals)
                    {
                        <option value="@item.Id" selected="@item.IsDefault">@item.Amount грн.</option>
                    }
                </select>

                @Html.ValidationMessageFor(model => model.NominalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Створити" class="btn btn-primary btn-loading" data-loading-text="Створення..." />
            </div>
        </div>
    </div>
}

<div id="create-result"></div>

<div>
    @Html.ActionLink("Назад до списку", "Index")
</div>

@section scripts {
    @Scripts.Render("~/Scripts/package-create.js")
}

TicketManagementSystem.Web/Views/Package/Delete.cshtml
@model TicketManagementSystem.Web.PackageDetailsModel

@{
    ViewBag.Title = $"Видалення пачки \"{Model.Name}\"";
}

<h2>@ViewBag.Title</h2>

<div id="package-delete-grid">
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>

        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        @if (!string.IsNullOrEmpty(Model.ColorName))
        {
            <dt>@Html.DisplayNameFor(model => model.ColorName)</dt>
            <dd>@Html.DisplayFor(model => model.ColorName)</dd>
        }

        @if (!string.IsNullOrEmpty(Model.SerialName))
        {
            <dt>@Html.DisplayNameFor(model => model.SerialName)</dt>
            <dd>@Html.DisplayFor(model => model.SerialName)</dd>
        }

        @if (!string.IsNullOrEmpty(Model.Note))
        {
            <dt>@Html.DisplayNameFor(model => model.Note)</dt>
            <dd>@Html.DisplayFor(model => model.Note)</dd>
        }

        <dt>@Html.DisplayNameFor(model => model.TicketsCount)</dt>
        <dd>@Html.DisplayFor(model => model.TicketsCount)</dd>
    </dl>

    @if (Model.TicketsCount == 0)
    {
        using (Ajax.BeginForm("Delete", new AjaxOptions
        {
            UpdateTargetId = "package-delete-grid",
            InsertionMode = InsertionMode.Replace
        }))
        {
            @Html.AntiForgeryToken()

            <h5>Ви дійсно хочете повністю видалити пачку "@Model.Name"?</h5>

            <div class="form-actions no-color">
                <input type="submit" value="Видалити" class="btn btn-default" />
            </div>
        }
    }
    else
    {
        @Html.AlertWarning("Неможливо видалити цю пачку, оскільки є квитки, що до неї належать.")
    }
</div>

TicketManagementSystem.Web/Views/Package/DeletePartial.cshtml
@model TicketManagementSystem.Web.PackageDetailsModel

<h2>Видалення пачки "@Model.Name"</h2>

<div id="package-delete-grid">
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>

        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        @if (!string.IsNullOrEmpty(Model.ColorName))
        {
            <dt>@Html.DisplayNameFor(model => model.ColorName)</dt>
            <dd>@Html.DisplayFor(model => model.ColorName)</dd>
        }

        @if (!string.IsNullOrEmpty(Model.SerialName))
        {
            <dt>@Html.DisplayNameFor(model => model.SerialName)</dt>
            <dd>@Html.DisplayFor(model => model.SerialName)</dd>
        }

        @if (!string.IsNullOrEmpty(Model.Note))
        {
            <dt>@Html.DisplayNameFor(model => model.Note)</dt>
            <dd>@Html.DisplayFor(model => model.Note)</dd>
        }

        <dt>@Html.DisplayNameFor(model => model.TicketsCount)</dt>
        <dd>@Html.DisplayFor(model => model.TicketsCount)</dd>
    </dl>

    @if (Model.TicketsCount == 0)
    {
        using (Ajax.BeginForm("Delete", new AjaxOptions
        {
            UpdateTargetId = "package-delete-grid",
            InsertionMode = InsertionMode.Replace,
            OnSuccess = "OnSuccess",
            OnBegin = "OnBegin",
            OnComplete = "OnComplete",

            Confirm = $"Дійсно видалити пачку \"{Model.Name}\"?"
        }))
        {
            @Html.AntiForgeryToken()

            <h5>Ви дійсно хочете повністю видалити пачку "@Model.Name"?</h5>

            <div class="form-actions no-color">
                <input type="submit" value="Видалити" class="btn btn-danger btn-loading" data-loading-text="Видалення..." />
            </div>
            <br />
        }
    }
    else
    {
        @Html.AlertDanger("Неможливо видалити цю пачку, оскільки є квитки, що до неї належать.")
    }
</div>

TicketManagementSystem.Web/Views/Package/FilterFormPartial.cshtml
@model PackageFilterModel

@using(Html.BeginForm("Filter", "Package", FormMethod.Get))
{
    <hr />

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.FirstNumber, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FirstNumber, Model.Numbers, "(Будь-яка)", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorId, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ColorId, Model.Colors, "(Будь-який)", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialId, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SerialId, Model.Series, "(Будь-яка)", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, EnumHelper.GetSelectList(typeof(TicketManagementSystem.Business.Enums.PackageStatusFilter)), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Застосувати фільтр" />
            </div>
        </div>
    </div>
}

TicketManagementSystem.Web/Views/Package/MoveUnallocatedModal.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>

        <h4 class="modal-title">Квитки, які можна перемістити до пачки</h4>
    </div>

    <div class="modal-body">
        <div id="loading-message" style="display:none">Завантаження...</div>
        <div id="move-result"></div>
        <div id="ticket-list"></div>
    </div>
</div>

TicketManagementSystem.Web/Views/Package/SearchPartial.cshtml
@model IEnumerable<PackageDetailsModel>

<div class="panel panel-default">
    <div class="panel-heading">Результати пошуку</div>
    <div class="panel-body">Пачок знайдено: @Model.Count()</div>

    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <tr>
                <th>ID</th>
                <th>Назва</th>
                <th>Квитків</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@Html.ActionLink(item.Name, "Details", "Package", new { id = item.Id }, new { target = "_blank" }) <sup>@item.Nominal</sup></td>
                    <td>@item.TicketsCount</td>
                </tr>
            }
        </table>
    </div>
</div>