TicketManagementSystem.Web/Controllers/ReportController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using TicketManagementSystem.Business.Extensions;
using TicketManagementSystem.Business.Interfaces;

namespace TicketManagementSystem.Web.Controllers
{
    public class ReportController : BaseController
    {
        private readonly IReportService _reportService;

        public ReportController(IReportService reportService)
        {
            _reportService = reportService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            // Model is last report.
            return View(_reportService.GetLastReport());
        }

        [HttpGet, OutputCache(Duration = 30, Location = OutputCacheLocation.Client)]
        public ActionResult Archive()
        {
            var reports = _reportService.GetReports()
                .OrderByDescending(r => r.Date)
                .GroupBy(r => r.Date.ToString("MMMM yyyy"))
                .ToDictionary(g => g.Key.FirstCharToUpper(), g => g.AsEnumerable());

            return View(reports);
        }

        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin")]
        public ActionResult CreateReport()
        {
            var report = _reportService.CreateReport(false);
            var folderPath = Request.RequestContext.HttpContext.Server.MapPath("~/Files/Reports/");

            var isSuccess = _reportService.TryCreatePDFs(report,
                    action => Request.Url.Authority + Url.Action(action),
                    fileName => $"{folderPath}{fileName}.pdf");

            if (!isSuccess)
                return HttpBadRequest();

            _reportService.SaveReport(report);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DefaultReportPrint()
        {
            return View(_reportService.GetDefaultReportDTO());
        }

        [HttpGet]
        public ActionResult PackagesReportPrint()
        {
            return View(_reportService.GetPackagesReportDTO());
        }
    }
}

TicketManagementSystem.Web/Controllers/StatisticsController.cs
using System.Web.Mvc;
using System.Web.UI;

namespace TicketManagementSystem.Web.Controllers
{
    [OutputCache(Duration = 30, Location = OutputCacheLocation.ServerAndClient)]
    public class StatisticsController : Controller
    {
        public ActionResult Index(int? id) => View("~/Views/Statistics/Engine/Index.cshtml", id);

        public ActionResult Legacy() => View("~/Views/Statistics/Index.cshtml");

        public ActionResult Monthly() => View();
    }
}

TicketManagementSystem.Web/Views/Shared/ErrorListPartial.cshtml
@model IEnumerable<string>

<div class="alert alert-danger" role="alert">
    <ul>
        @foreach (var error in Model)
        {
            <li>@error</li>
        }
    </ul>
</div>

TicketManagementSystem.Web/Views/Shared/LoadingSpinner.cshtml
<div id="loading" class="loading-spinner" style="display: none;">
    <img src="~/Content/loading-spinner-black.gif" />
</div>

TicketManagementSystem.Web/Views/Shared/Modal.cshtml
<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="modal-window-label">
    <div id="modal-window-content" class="modal-dialog" role="document"></div>
</div>

TicketManagementSystem.Web/Views/Shared/SelectListPartial.cshtml
@model SelectListModel

<select id="@Model.Id" name="@Model.Name" class="form-control">
    @if (!string.IsNullOrEmpty(Model.DefaultOption))
    {
        <option value>@Model.DefaultOption</option>
    }

    @foreach (var opt in Model.Options)
    {
        <option value="@opt.Value">@opt.Text</option>
    }
</select>

TicketManagementSystem.Web/Views/Shared/SuccessAlertLinkPartial.cshtml
<div class="alert alert-success" role="alert">
    @(ViewBag.Message as string)<br />
    <a href="@(ViewBag.Url as string)" class="alert-link"><b>@(ViewBag.UrlMessage as string)</b></a>
</div>

TicketManagementSystem.Web/Views/Shared/SuccessAlertPartial.cshtml
@Html.AlertSuccess(ViewBag.Message as string)

TicketManagementSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Ticket Management System</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery.tipsy/1.0.3/jquery.tipsy.min.css")

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ticket MS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Головна", "Index", "Home")</li>
                    <li>@Html.ActionLink("Кольори", "Index", "Color")</li>
                    <li>@Html.ActionLink("Серії", "Index", "Serial")</li>
                    <li>@Html.ActionLink("Пачки", "Index", "Package")</li>
                    <li>@Html.ActionLink("Квитки", "Index", "Ticket")</li>
                    <li>@Html.ActionLink("Статистика", "Index", "Statistics")</li>
                    <li>@Html.ActionLink("Звіти", "Index", "Report")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink(User.Identity.Name, "Index", "Account")</li>
                        <li>@Html.ActionLink("Вийти", "Logout", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Увійти", "Login", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; 2017 - @DateTime.Now.Year</p>
        </footer>

        @Html.Partial("Modal")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery.tipsy/1.0.3/jquery.tipsy.min.js")

    @Scripts.Render("~/Scripts/site.js")

    @RenderSection("scripts", required: false)
</body>
</html>